### ISSUE TITLE
[Feature] Examples of Cloning Audio and Text with One-Shot TTS and Streaming Output

### ISSUE THREAD

**Issue by IrisSally** [lenML/ChatTTS-Forge#130]
### 确认清单

- [X] 我已经仔细阅读[项目文档](https://github.com/lenML/ChatTTS-Forge/blob/master/README.md)，确认现有功能无法解决我的需求
- [X] 我已经检索过现有[issue](https://github.com/lenML/ChatTTS-Forge/issues)，确认与现有issue的内容并不重复
- [X] 确认并非问题讨论而是 Feature request

### 功能描述

I need to clone an audio file along with its corresponding text. Using ChatTTS's one-shot feature, I aim to replicate the voice and generate a new piece of text. Could you provide guidance on how to utilize APIs (such as TTS, Google, OpenAI, etc.) to achieve this? Additionally, I require the output to be streamed. Are there any recent examples of using these APIs, particularly for one-shot and streaming generation? Your assistance is greatly appreciated.

![Snipaste_2024-08-05_10-58-48](https://github.com/user-attachments/assets/7a1f046f-2e48-4244-878a-295d19096c5a)

**Comment by zhzLuke96** [comment]
Yes, the one-shot feature has just been implemented. We're currently lacking detailed documentation, but we plan to improve this before the next version (0.8) is released.

**Comment by zhzLuke96** [comment]
Since many users might have similar questions, I'll briefly explain how to use the one-shot feature:

Currently, there's no direct webui/API to use a "reference audio". Instead:

1. Create a "speaker" with the reference audio configured.
2. When using any interface, specify the created "speaker".

How to create a `speaker`:
- In the webui, use the "builder" tab in the "speaker" section to create a speaker with reference audio.

How to use the `speaker`:
- In webui: Upload the generated `.spkv1.json` file in the "upload speaker" section.
- In API: Place the `.spkv1.json` file in the `./data/speakers` folder. When making a request, specify the corresponding speaker name. For example, in the Google-like API you screenshot, modify `voice.name` to your desired speaker.

For the streaming output, our current APIs support this feature. Simply set the stream parameter to true in the API configuration. You can refer to the examples in our documentation (or `/docs` endpoint) for specific implementation details. It's worth noting that the Google-like API doesn't support streaming as it returns data in JSON format.

We're continuously working on improving and expanding our features. If you have any further questions or need more specific examples, feel free to ask!

**Comment by IrisSally** [comment]
I appreciate your assistance. I'll try it out.

**Comment by zhzLuke96** [comment]
Update:

- After commit f30d45bceafd58e6e2e2db6e10d7b1ad09bf2d92, the reference audio feature was added under the TTS tab, allowing direct inference using reference audio.
- After commit e68fa33ff9b1820749e6e73e216d764b221050e4, the OpenVoice model can be used for voice cloning in the API.

This issue should no longer require discussion, so it can be closed.
